server:
  port: 28081
spring:
  application:
    name: my-eureka-server
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    remoteRegionUrlsWithName:
      region-west: http://${spring.security.user.name}:${spring.security.user.password}@localhost:28083/eureka/
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: region-east
    service-url:
      zone1: http://${spring.security.user.name}:${spring.security.user.password}@localhost:28081/eureka/
      zone2: http://${spring.security.user.name}:${spring.security.user.password}@localhost:28082/eureka/
    availability-zones:
      region-east: zone1, zone2
  instance:
    hostname: localhost
#    preferIpAddress: true
    metadataMap.zone: zone1