server:
  port: 28102
spring:
  application:
    name: my-zuul-gateway-server
  zipkin:
    baseUrl: http://localhost:9411/
eureka:
  instance:
    metadataMap.zone: zone3
  client:
    security:
      basic:
        user: admin
        password: admin
    registerWithEureka: true
    fetchRegistry: true
    region: region-west
    service-url:
      zone3: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:28083/eureka/
      zone4: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:28084/eureka/
    availability-zones:
      region-west: zone3, zone4

logging:
  level:
    root: INFO
